export const seedUsers = [
  {
    email: "admin@fieldsight.local",
    password: "Admin123!",
    name: "Admin",
    role: "admin"
  },
  {
    email: "crew1@fieldsight.local",
    password: "Field123!",
    name: "MasTec East Fiber Crew",
    role: "field"
  }
];

export const seedCrews = [
  ["MasTec East Fiber Crew", "Internal team", 9, "Primary Miami-Dade fiber splice and restoration crew.", "Jordan Reyes", "jordan.reyes@fieldsight.local", "(305) 555-0142", "Miami-Dade County fiber response"]
];

export const seedJobs = [
  {
    title: "Brickell City Centre Fiber Entry Review",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "701 S Miami Ave, Miami, FL 33131",
    jobType: "Fiber splice",
    jobDescription: "Uploaded scope for a lobby-side fiber entry review and splice planning pass at Brickell City Centre.",
    priority: "High",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-07T08:00:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 285000,
    laborCost: 118000,
    plannedHours: 12,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Venetian Pool Conduit Path Verification",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "2701 De Soto Blvd, Coral Gables, FL 33134",
    jobType: "Conduit inspection",
    jobDescription: "Uploaded scope to verify conduit path and handhole conditions near the Venetian Pool service corridor.",
    priority: "Medium",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-07T09:30:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 164000,
    laborCost: 72000,
    plannedHours: 8,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Vizcaya Gate Fiber Restoration Prep",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "3251 S Miami Ave, Miami, FL 33129",
    jobType: "Fiber restoration",
    jobDescription: "Uploaded prep package for a restoration review at the Vizcaya entrance and roadside pull box.",
    priority: "High",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-07T11:00:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 242000,
    laborCost: 101000,
    plannedHours: 10,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "PAMM Backbone Label Audit",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "1103 Biscayne Blvd, Miami, FL 33132",
    jobType: "Fiber audit",
    jobDescription: "Uploaded scope to confirm labeling, slack storage, and splice map alignment near Perez Art Museum Miami.",
    priority: "Medium",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-07T12:30:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 138000,
    laborCost: 61000,
    plannedHours: 6,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Frost Science Fiber Route Check",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "1101 Biscayne Blvd, Miami, FL 33132",
    jobType: "Route validation",
    jobDescription: "Uploaded route check to confirm museum-side fiber path, handhole access, and test point readiness at Frost Science.",
    priority: "Medium",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-07T13:30:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 151000,
    laborCost: 66000,
    plannedHours: 7,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Bayfront Park Event Fiber Standby",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "301 Biscayne Blvd, Miami, FL 33131",
    jobType: "Field support",
    jobDescription: "Uploaded standby package for temporary event-side fiber support and quick test verification at Bayfront Park.",
    priority: "Low",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-08T08:00:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 97000,
    laborCost: 42000,
    plannedHours: 5,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Bayside Marketplace Demarc Review",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "401 Biscayne Blvd, Miami, FL 33132",
    jobType: "Demarc inspection",
    jobDescription: "Uploaded demarc review for bayside retail connectivity and back-of-house fiber labeling validation.",
    priority: "Medium",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-08T09:15:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 144000,
    laborCost: 63000,
    plannedHours: 6,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Kaseya Center MDF Fiber Survey",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "601 Biscayne Blvd, Miami, FL 33132",
    jobType: "MDF survey",
    jobDescription: "Uploaded survey package to inspect MDF entry conditions and confirm arena-side fiber slack availability.",
    priority: "High",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-08T10:30:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 318000,
    laborCost: 133000,
    plannedHours: 12,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Adrienne Arsht Center Fiber Turn-Up Prep",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "1300 Biscayne Blvd, Miami, FL 33132",
    jobType: "Turn-up preparation",
    jobDescription: "Uploaded turn-up prep for performance venue connectivity and equipment-room patch review at the Arsht Center.",
    priority: "High",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-08T12:00:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 226000,
    laborCost: 97000,
    plannedHours: 9,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  },
  {
    title: "Freedom Tower Handhole Inspection",
    market: "Miami, FL",
    requestedBy: "MasTec Miami Dispatch",
    jobAddress: "600 Biscayne Blvd, Miami, FL 33132",
    jobType: "Handhole inspection",
    jobDescription: "Uploaded inspection package to document handhole condition, label integrity, and route continuity by Freedom Tower.",
    priority: "Medium",
    intakeStatus: "Uploaded",
    scheduledStartAt: "2026-05-08T13:30:00",
    assignedTo: null,
    fieldStatus: "Uploaded",
    completion: 0,
    jobValue: 133000,
    laborCost: 58000,
    plannedHours: 6,
    actualHours: 0,
    blockerReason: "",
    issue: "Job uploaded and awaiting dispatcher assignment.",
    qualityScore: 90,
    durationVariance: 0
  }
];
